config/routes.rb
Rails.application.routes.draw do
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users
  root 'sweets#index'
  get 'sweets/spring' => 'sweets#spring'
  get 'sweets/summer' => 'sweets#summer'
  get 'sweets/autumn' => 'sweets#autumn'
  get 'sweets/winter' => 'sweets#winter'

  get 'sweets/search' => 'sweets#search' 
  get 'search', to: 'sweets#index', as: 'search_sweets'
  get 'sweets/itiran' => 'sweets#itiran' 

  
  

  resources :sweets do
    resources :comments, only: [:create]
  end
  
 
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :sweet
end

app/models/sweet.rb
class Sweet < ApplicationRecord
    mount_uploader :image, ImageUploader

    belongs_to :user
    has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :sweets, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!

    def create
      sweet = Sweet.find(params[:sweet_id])
      comment = sweet.comments.build(comment_params) #buildを使い、contentとtweet_idの二つを同時に代入
      comment.user_id = current_user.id
      if comment.save
        flash[:success] = "コメントしました"
        redirect_back(fallback_location: root_path) #直前のページにリダイレクト
      else
        flash[:success] = "コメントできませんでした"
        redirect_back(fallback_location: root_path) #直前のページにリダイレクト
      end
    end
    private

    def comment_params
      params.require(:comment).permit(:content)
    end
end

app/controllers/sweets_controller.rb
class SweetsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :spring, :summer, :autumn, :winter, :show]
  def index 
    if params[:search] == nil
      @sweets= Sweet.all
     elsif params[:search] == ''
      @sweets= Sweet.all
     else
      @sweets = Sweet.where("name LIKE ? or about LIKE ? ",'%' + params[:search] + '%','%' + params[:search] + '%')
    end
  
  end


 def search
 end

def itiran
  @sweets= Sweet.all
end

    def new
      @sweet = Sweet.new
    end

      def create
        sweet = Sweet.new(sweet_params)

        sweet.user_id = current_user.id

        if sweet.save
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
      end

      def show
        @sweet = Sweet.find(params[:id])
        @comments = @sweet.comments
        @comment = Comment.new
      end

      def edit
        @sweet = Sweet.find(params[:id])
      end

      def update
        sweet = Sost.find(params[:id])
        if sweet.update(sweet_params)
          redirect_to :action => “show”, :id => sweet.id
        else
          redirect_to :action => “new”
        end
      end
      def destroy
        sweet = Sweet.find(params[:id])
        sweet.destroy
        redirect_to action: :index
      end

      def spring
        @springs=Sweet.where(genre:"春")
      end
      
      def summer
        @summers=Sweet.where(genre:"夏")
      end
      
      def autumn
        @autumns=Sweet.where(genre:"秋")
      end

      def winter
        @winters=Sweet.where(genre:"冬")
      end

      private
      def sweet_params
        params.require(:sweet).permit(:image, :genre, :shashin, :name, :about, :url)
      end

  
    end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sweets_helper.rb
module SweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Aoki</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  
  <body>
<header>
<% if user_signed_in? %>
<div class="logout">
   <%= button_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %>
   </div>

 <% else %>

 <div class="login">
 <%= button_to 'ログイン', user_session_path, class: "login" %>
</div>
<% end %>
       
</header>
<main>
  <%= yield %>
</main>


  </body>
</html>

app/views/sweets/autumn.html.erb
<div class="autumn">


<div class="container4">
 <div class="aut">
 <%= image_tag "aki3.jpg"%>
 <h3>秋の和菓子</h3>
 </div>


 <div class="aut1">
    モンブランどらやき<br>
    <h4><%= link_to "詳細へ", sweet_path(t.id) %></h4>
 </div>

 <div class="aut2">
   月兎<br>
 <h4><%= link_to "詳細へ", sweet_path(t.id) %></h4>
 </div>

 <div class="aut3">
  上生菓子<br>
  <h4><%= link_to "詳細へ", sweet_path(t.id) %></h4>
 </div>

 <div class="aut4">
  フルーツ<br>あんみつ<br>
  <h4><%= link_to "詳細へ", sweet_path(t.id) %></h4>
 </div>
</div>
<%= link_to "トップページ", sweets_path %>


</div>

app/views/sweets/edit.html.erb
<%= form_for @sweet do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, :size => 140 %> 
    
    <%= f.label :genre %>
    <%= f.text_field :genre, :size => 140 %> 

    <%= f.label :about %>
    <%= f.text_field :about, :size => 140 %> 

    <%= f.label :url %>
    <%= f.text_field :url, :size => 140 %> 

    
    
    
    
    
    <%= f.submit "編集する" %>
  <% end %>

app/views/sweets/index.html.erb
<div class="main">

<div class="search-form-6">   
<%= form_tag({controller:"sweets",action:"index"}, method: :get) do %>
<%= text_field_tag :search, nil, placeholder: "キーワードで検索" %>
<% end %>
</div>

<%if params[:search] != "" && params[:search] != nil%>

 <div class="search-container">
    <% @sweets.each do |t| %>
      <div class="">
      
       <%= image_tag t.image_url, size: "500x400" if t.image? %>
       <%= t.name %>
       
        <%= link_to "詳細へ", sweet_path(t.id) %>
    
        
        </div>
      <% end %>

 <%else%>
 <div class="square">

   <div class="text">
    <h1>めぐりあい</h1>
   </div>
 </div>
  <div class="topimage3">
   <div class="topimage2">
      <div class="image src1" class="absolute"></div>
      <div class="image src2" class="absolute"></div>
      <div class="image src3" class="absolute"></div>
    </div>
  </div>

  

  <div class="explanation">
  <h2>「おいしい」も「かわいい」も好き。</h2>
  <h3>洋菓子に比べて手に取られにくい和菓子。</h3>
  <h4>けれど繊細な手作業によって生まれる和菓子特有の良さも知ってもらえたら・・・</h4>
  <h5>そんな気持ちで生まれたサイトです。</h5>
  <h6>Click your favorite season↓</h6>

  <div class="container">
   <div class="springimg">
    <%= link_to sweets_spring_path do %>
    <%= image_tag "spring.2.jpg"%>
    <p>春</p>
    <% end %>
   </div>

   <div class="summerimg">
   <%= link_to sweets_summer_path do %>
    <%= image_tag "summer.3.jpg"%>
    <p>夏</p>
    <% end %>
   </div>

   <div class="autumnimg">
   <%= link_to sweets_autumn_path do %>
    <%= image_tag "autumn.jpg"%>
    <p>秋</p>
   <% end %>
   </div>

   <div class="winterimg">
   <%= link_to sweets_winter_path do %>
    <%= image_tag "winter.jpg"%>
    <p>冬</p>
   <% end %>
  </div>

  



 </div>
</div>
<%end%>

app/views/sweets/itiran.html.erb
<div class="tweets-container">
    <% @sweets.each do |t| %>
      <div class="">
      <%= t.user.email %>
       <%= image_tag t.image_url, size: "500x400" if t.image? %>
        <%= t.genre %>

        <%= t.created_at %>
        <%= link_to "詳細へ", sweet_path(t.id) %>
        <%= link_to "編集する", edit_sweet_path(t.id) %>
        <%= link_to "新規投稿ページへ", new_sweet_path(t.id) %>
        <%= link_to "削除する", sweet_path(t.id), method: :delete %>

        </div>
      <% end %>

app/views/sweets/new.html.erb
<h1>めぐりあい</h1>
<%= button_to 'ログアウト', destroy_user_session_path, method: :delete %>
<h3>新規投稿ページ</h3>
<%= form_for @sweet do |f| %>

   

  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <div class="field">
  <%= f.label :genre %>

  <%= f.select :genre, 
  [["春", "春"], 
  ["夏", "夏"], 
  ["秋", "秋"],
  ["冬", "冬"]], include_blank: "選択して下さい" %>
</div>
  </div>

  <div class="field">
  <%= f.label :name %>
  <%= f.text_field :name %>
  </div>

  <div class="field">
  <%= f.label :about %>
  <%= f.text_field :about %>
  </div>

  <div class="field">
  <%= f.label :url %>
  <%= f.text_field :url %>
  </div>
  
  <%= f.submit "Tweetする" %>
  <% end %>

app/views/sweets/show.html.erb
<div class="show">

<div class="tweet">
  <%= image_tag @sweet.image_url, size: "500x400" if @sweet.image? %>
  <p><%= @sweet.name%></p>
  <p><%= @sweet.about %></p>
  <p><%= @sweet.url %></p>
</div>

<div class="comment-wrapper">
  <p>コメント一覧</p>
  <% @comments.each do |c| %>
    <div>
      <%= c.user.email unless c.user.blank? %>
      <br>
      <%= c.content %>
    </div>
      <br>
  <% end %>

  <% if user_signed_in? %>
    <%= form_with(model: [@sweet, @comment], local: true) do |f| %>
      <%= f.text_area :content %>
      <%= button_tag type: "submit" do %>
        <i class="far fa-comments"></i> コメントする
      <% end %>
    <% end %>
  <% end %>
</div>

<%= link_to "トップページ", sweets_path %>
</div>

app/views/sweets/spring.html.erb
<div class="spring">

    
    <div class="container2">
    <div class="spr">
    <%= image_tag "haru.jpg"%>
    </div>
    <h3>春の和菓子</h3>

    <div class="spr1">
    感謝の花<br>
    <h4><%= link_to "詳細へ", sweet_path(t.id) %></h4>
    </div>

    <div class="spr2">
    豆乳どら焼き桜餡<br>
    <h4><%= link_to "詳細へ", sweet_path(t.id) %></h4>
    </div>

    <div class="spr3">
    桜もなか<br>
    <h4><%= link_to "詳細へ", sweet_path(t.id) %></h4>
    </div>

    <div class="spr4">
    焼き鳳瑞<br>
    <h4><%= link_to "詳細へ", sweet_path(t.id) %></h4>
    </div>
    </div>

    <%= link_to "トップページ", sweets_path %>


</div>

app/views/sweets/summer.html.erb
<div class="summer">


<div class="container3">
 <div class="sum">
 <%= image_tag "natu2.jpg"%>
 <h3>夏の和菓子</h3>
 </div>

 <div class="sum1">
    仙台七夕水まんじゅう<br>
    <h4><%= link_to "詳細へ", sweet_path(t.id) %></h4>
 </div>

 <div class="sum2">
    鴻池花火<br>
    <h4><%= link_to "詳細へ", sweet_path(t.id) %></h4>
 </div>

 <div class="sum3">
    向日葵<br>
    <h4><%= link_to "詳細へ", sweet_path(t.id) %></h4>
 </div>

 <div class="sum4">
    登り鮎<br>
    <h4><%= link_to "詳細へ", sweet_path(t.id) %></h4>
 </div>
</div>

<%= link_to "トップページ", sweets_path %>


</div>

app/views/sweets/winter.html.erb
<div class="winter">


<div class="container5">
 <div class="win">
 <%= image_tag "fuyu2.jpg"%>
 <h3>冬の和菓子</h3>
 </div>

 <div class="win1">
    うぐいす餅<br>
    <h4><%= link_to "詳細へ", sweet_path(t.id) %></h4>
 </div>

 <div class="win2">
    kuki<br>
    <h4><%= link_to "詳細へ", sweet_path(t.id) %></h4>
 </div>

 <div class="win3">
    花びら餅<br>
    <h4><%= link_to "詳細へ", sweet_path(t.id) %></h4>
 </div>

 <div class="win4">
   林檎<br>
 <h4><%= link_to "詳細へ", sweet_path(t.id) %></h4>
</div>


<%= link_to "トップページ", sweets_path %>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>